# GameManager framework configuration file
ai: "ai.hannibal.HannibalBot"
auto_join: "custom/test" # 1v1, ffa, custom/<custom room name>. if empty or invalid, ask user.
sign_in_mode: false # sign in to generals.io
bot_username: 'HannibalAI'
websocket_connection_delay: 1