# GameManager framework configuration file
ai: "ai.hannibal.HannibalBot"
driver: "chrome" # chrome, firefox, edge, safari
auto_join: "ffa" # 1v1, ffa, custom/<custom room name>. if empty or invalid, ask user.